//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.8
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class example {
  public static void trigger_log(string message, STR_CALLBACK str_callback) {
    examplePINVOKE.trigger_log(message, str_callback);
  }

  public static int run_op(int a, int b, OP_CALLBACK my_operator) {
    int ret = examplePINVOKE.run_op(a, b, my_operator);
    return ret;
  }

}
