/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class adapter_t {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected adapter_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(adapter_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pc_ble_driver_sd_api_v5JNI.delete_adapter_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setInternal(long value) {
    pc_ble_driver_sd_api_v5JNI.adapter_t_internal_set(swigCPtr, this, value);
  }

  public long getInternal() {
        long cPtr = pc_ble_driver_sd_api_v5JNI.adapter_t_internal_get(swigCPtr, this);
        return cPtr;
    }

  public adapter_t() {
    this(pc_ble_driver_sd_api_v5JNI.new_adapter_t(), true);
  }

}
