/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class ble_gatt_char_props_t {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ble_gatt_char_props_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ble_gatt_char_props_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pc_ble_driver_sd_api_v5JNI.delete_ble_gatt_char_props_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setBroadcast(short value) {
    pc_ble_driver_sd_api_v5JNI.ble_gatt_char_props_t_broadcast_set(swigCPtr, this, value);
  }

  public short getBroadcast() {
    return pc_ble_driver_sd_api_v5JNI.ble_gatt_char_props_t_broadcast_get(swigCPtr, this);
  }

  public void setRead(short value) {
    pc_ble_driver_sd_api_v5JNI.ble_gatt_char_props_t_read_set(swigCPtr, this, value);
  }

  public short getRead() {
    return pc_ble_driver_sd_api_v5JNI.ble_gatt_char_props_t_read_get(swigCPtr, this);
  }

  public void setWrite_wo_resp(short value) {
    pc_ble_driver_sd_api_v5JNI.ble_gatt_char_props_t_write_wo_resp_set(swigCPtr, this, value);
  }

  public short getWrite_wo_resp() {
    return pc_ble_driver_sd_api_v5JNI.ble_gatt_char_props_t_write_wo_resp_get(swigCPtr, this);
  }

  public void setWrite(short value) {
    pc_ble_driver_sd_api_v5JNI.ble_gatt_char_props_t_write_set(swigCPtr, this, value);
  }

  public short getWrite() {
    return pc_ble_driver_sd_api_v5JNI.ble_gatt_char_props_t_write_get(swigCPtr, this);
  }

  public void setNotify(short value) {
    pc_ble_driver_sd_api_v5JNI.ble_gatt_char_props_t_notify_set(swigCPtr, this, value);
  }

  public short getNotify() {
    return pc_ble_driver_sd_api_v5JNI.ble_gatt_char_props_t_notify_get(swigCPtr, this);
  }

  public void setIndicate(short value) {
    pc_ble_driver_sd_api_v5JNI.ble_gatt_char_props_t_indicate_set(swigCPtr, this, value);
  }

  public short getIndicate() {
    return pc_ble_driver_sd_api_v5JNI.ble_gatt_char_props_t_indicate_get(swigCPtr, this);
  }

  public void setAuth_signed_wr(short value) {
    pc_ble_driver_sd_api_v5JNI.ble_gatt_char_props_t_auth_signed_wr_set(swigCPtr, this, value);
  }

  public short getAuth_signed_wr() {
    return pc_ble_driver_sd_api_v5JNI.ble_gatt_char_props_t_auth_signed_wr_get(swigCPtr, this);
  }

  public ble_gatt_char_props_t() {
    this(pc_ble_driver_sd_api_v5JNI.new_ble_gatt_char_props_t(), true);
  }

}
