/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class ble_gap_sec_levels_t {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ble_gap_sec_levels_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ble_gap_sec_levels_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pc_ble_driver_sd_api_v5JNI.delete_ble_gap_sec_levels_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setLv1(short value) {
    pc_ble_driver_sd_api_v5JNI.ble_gap_sec_levels_t_lv1_set(swigCPtr, this, value);
  }

  public short getLv1() {
    return pc_ble_driver_sd_api_v5JNI.ble_gap_sec_levels_t_lv1_get(swigCPtr, this);
  }

  public void setLv2(short value) {
    pc_ble_driver_sd_api_v5JNI.ble_gap_sec_levels_t_lv2_set(swigCPtr, this, value);
  }

  public short getLv2() {
    return pc_ble_driver_sd_api_v5JNI.ble_gap_sec_levels_t_lv2_get(swigCPtr, this);
  }

  public void setLv3(short value) {
    pc_ble_driver_sd_api_v5JNI.ble_gap_sec_levels_t_lv3_set(swigCPtr, this, value);
  }

  public short getLv3() {
    return pc_ble_driver_sd_api_v5JNI.ble_gap_sec_levels_t_lv3_get(swigCPtr, this);
  }

  public void setLv4(short value) {
    pc_ble_driver_sd_api_v5JNI.ble_gap_sec_levels_t_lv4_set(swigCPtr, this, value);
  }

  public short getLv4() {
    return pc_ble_driver_sd_api_v5JNI.ble_gap_sec_levels_t_lv4_get(swigCPtr, this);
  }

  public ble_gap_sec_levels_t() {
    this(pc_ble_driver_sd_api_v5JNI.new_ble_gap_sec_levels_t(), true);
  }

}
