/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class ble_gap_sec_kdist_t {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ble_gap_sec_kdist_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ble_gap_sec_kdist_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pc_ble_driver_sd_api_v5JNI.delete_ble_gap_sec_kdist_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setEnc(short value) {
    pc_ble_driver_sd_api_v5JNI.ble_gap_sec_kdist_t_enc_set(swigCPtr, this, value);
  }

  public short getEnc() {
    return pc_ble_driver_sd_api_v5JNI.ble_gap_sec_kdist_t_enc_get(swigCPtr, this);
  }

  public void setId(short value) {
    pc_ble_driver_sd_api_v5JNI.ble_gap_sec_kdist_t_id_set(swigCPtr, this, value);
  }

  public short getId() {
    return pc_ble_driver_sd_api_v5JNI.ble_gap_sec_kdist_t_id_get(swigCPtr, this);
  }

  public void setSign(short value) {
    pc_ble_driver_sd_api_v5JNI.ble_gap_sec_kdist_t_sign_set(swigCPtr, this, value);
  }

  public short getSign() {
    return pc_ble_driver_sd_api_v5JNI.ble_gap_sec_kdist_t_sign_get(swigCPtr, this);
  }

  public void setLink(short value) {
    pc_ble_driver_sd_api_v5JNI.ble_gap_sec_kdist_t_link_set(swigCPtr, this, value);
  }

  public short getLink() {
    return pc_ble_driver_sd_api_v5JNI.ble_gap_sec_kdist_t_link_get(swigCPtr, this);
  }

  public ble_gap_sec_kdist_t() {
    this(pc_ble_driver_sd_api_v5JNI.new_ble_gap_sec_kdist_t(), true);
  }

}
