/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class ble_common_opt_t {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ble_common_opt_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ble_common_opt_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pc_ble_driver_sd_api_v5JNI.delete_ble_common_opt_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setPa_lna(ble_common_opt_pa_lna_t value) {
    pc_ble_driver_sd_api_v5JNI.ble_common_opt_t_pa_lna_set(swigCPtr, this, ble_common_opt_pa_lna_t.getCPtr(value), value);
  }

  public ble_common_opt_pa_lna_t getPa_lna() {
    long cPtr = pc_ble_driver_sd_api_v5JNI.ble_common_opt_t_pa_lna_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ble_common_opt_pa_lna_t(cPtr, false);
  }

  public void setConn_evt_ext(ble_common_opt_conn_evt_ext_t value) {
    pc_ble_driver_sd_api_v5JNI.ble_common_opt_t_conn_evt_ext_set(swigCPtr, this, ble_common_opt_conn_evt_ext_t.getCPtr(value), value);
  }

  public ble_common_opt_conn_evt_ext_t getConn_evt_ext() {
    long cPtr = pc_ble_driver_sd_api_v5JNI.ble_common_opt_t_conn_evt_ext_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ble_common_opt_conn_evt_ext_t(cPtr, false);
  }

  public ble_common_opt_t() {
    this(pc_ble_driver_sd_api_v5JNI.new_ble_common_opt_t(), true);
  }

}
