/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class ble_cfg_t {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ble_cfg_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ble_cfg_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pc_ble_driver_sd_api_v5JNI.delete_ble_cfg_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setConn_cfg(ble_conn_cfg_t value) {
    pc_ble_driver_sd_api_v5JNI.ble_cfg_t_conn_cfg_set(swigCPtr, this, ble_conn_cfg_t.getCPtr(value), value);
  }

  public ble_conn_cfg_t getConn_cfg() {
    long cPtr = pc_ble_driver_sd_api_v5JNI.ble_cfg_t_conn_cfg_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ble_conn_cfg_t(cPtr, false);
  }

  public void setCommon_cfg(ble_common_cfg_t value) {
    pc_ble_driver_sd_api_v5JNI.ble_cfg_t_common_cfg_set(swigCPtr, this, ble_common_cfg_t.getCPtr(value), value);
  }

  public ble_common_cfg_t getCommon_cfg() {
    long cPtr = pc_ble_driver_sd_api_v5JNI.ble_cfg_t_common_cfg_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ble_common_cfg_t(cPtr, false);
  }

  public void setGap_cfg(ble_gap_cfg_t value) {
    pc_ble_driver_sd_api_v5JNI.ble_cfg_t_gap_cfg_set(swigCPtr, this, ble_gap_cfg_t.getCPtr(value), value);
  }

  public ble_gap_cfg_t getGap_cfg() {
    long cPtr = pc_ble_driver_sd_api_v5JNI.ble_cfg_t_gap_cfg_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ble_gap_cfg_t(cPtr, false);
  }

  public void setGatts_cfg(ble_gatts_cfg_t value) {
    pc_ble_driver_sd_api_v5JNI.ble_cfg_t_gatts_cfg_set(swigCPtr, this, ble_gatts_cfg_t.getCPtr(value), value);
  }

  public ble_gatts_cfg_t getGatts_cfg() {
    long cPtr = pc_ble_driver_sd_api_v5JNI.ble_cfg_t_gatts_cfg_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ble_gatts_cfg_t(cPtr, false);
  }

  public ble_cfg_t() {
    this(pc_ble_driver_sd_api_v5JNI.new_ble_cfg_t(), true);
  }

}
