/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class ble_gattc_evt_read_rsp_t {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ble_gattc_evt_read_rsp_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ble_gattc_evt_read_rsp_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pc_ble_driver_sd_api_v5JNI.delete_ble_gattc_evt_read_rsp_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setHandle(int value) {
    pc_ble_driver_sd_api_v5JNI.ble_gattc_evt_read_rsp_t_handle_set(swigCPtr, this, value);
  }

  public int getHandle() {
    return pc_ble_driver_sd_api_v5JNI.ble_gattc_evt_read_rsp_t_handle_get(swigCPtr, this);
  }

  public void setOffset(int value) {
    pc_ble_driver_sd_api_v5JNI.ble_gattc_evt_read_rsp_t_offset_set(swigCPtr, this, value);
  }

  public int getOffset() {
    return pc_ble_driver_sd_api_v5JNI.ble_gattc_evt_read_rsp_t_offset_get(swigCPtr, this);
  }

  public void setLen(int value) {
    pc_ble_driver_sd_api_v5JNI.ble_gattc_evt_read_rsp_t_len_set(swigCPtr, this, value);
  }

  public int getLen() {
    return pc_ble_driver_sd_api_v5JNI.ble_gattc_evt_read_rsp_t_len_get(swigCPtr, this);
  }

  public void setData(SWIGTYPE_p_unsigned_char value) {
    pc_ble_driver_sd_api_v5JNI.ble_gattc_evt_read_rsp_t_data_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getData() {
    long cPtr = pc_ble_driver_sd_api_v5JNI.ble_gattc_evt_read_rsp_t_data_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public ble_gattc_evt_read_rsp_t() {
    this(pc_ble_driver_sd_api_v5JNI.new_ble_gattc_evt_read_rsp_t(), true);
  }

}
