/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class ble_gattc_write_params_t {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ble_gattc_write_params_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ble_gattc_write_params_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pc_ble_driver_sd_api_v5JNI.delete_ble_gattc_write_params_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setWrite_op(short value) {
    pc_ble_driver_sd_api_v5JNI.ble_gattc_write_params_t_write_op_set(swigCPtr, this, value);
  }

  public short getWrite_op() {
    return pc_ble_driver_sd_api_v5JNI.ble_gattc_write_params_t_write_op_get(swigCPtr, this);
  }

  public void setFlags(short value) {
    pc_ble_driver_sd_api_v5JNI.ble_gattc_write_params_t_flags_set(swigCPtr, this, value);
  }

  public short getFlags() {
    return pc_ble_driver_sd_api_v5JNI.ble_gattc_write_params_t_flags_get(swigCPtr, this);
  }

  public void setHandle(int value) {
    pc_ble_driver_sd_api_v5JNI.ble_gattc_write_params_t_handle_set(swigCPtr, this, value);
  }

  public int getHandle() {
    return pc_ble_driver_sd_api_v5JNI.ble_gattc_write_params_t_handle_get(swigCPtr, this);
  }

  public void setOffset(int value) {
    pc_ble_driver_sd_api_v5JNI.ble_gattc_write_params_t_offset_set(swigCPtr, this, value);
  }

  public int getOffset() {
    return pc_ble_driver_sd_api_v5JNI.ble_gattc_write_params_t_offset_get(swigCPtr, this);
  }

  public void setLen(int value) {
    pc_ble_driver_sd_api_v5JNI.ble_gattc_write_params_t_len_set(swigCPtr, this, value);
  }

  public int getLen() {
    return pc_ble_driver_sd_api_v5JNI.ble_gattc_write_params_t_len_get(swigCPtr, this);
  }

  public void setP_value(long value) {
    pc_ble_driver_sd_api_v5JNI.ble_gattc_write_params_t_p_value_set(swigCPtr, this, value);
  }

  public long getP_value() {
        long cPtr = pc_ble_driver_sd_api_v5JNI.ble_gattc_write_params_t_p_value_get(swigCPtr, this);
        return cPtr;
    }

  public ble_gattc_write_params_t() {
    this(pc_ble_driver_sd_api_v5JNI.new_ble_gattc_write_params_t(), true);
  }

}
