/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class ble_gatts_attr_md_t {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ble_gatts_attr_md_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ble_gatts_attr_md_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pc_ble_driver_sd_api_v5JNI.delete_ble_gatts_attr_md_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setRead_perm(ble_gap_conn_sec_mode_t value) {
    pc_ble_driver_sd_api_v5JNI.ble_gatts_attr_md_t_read_perm_set(swigCPtr, this, ble_gap_conn_sec_mode_t.getCPtr(value), value);
  }

  public ble_gap_conn_sec_mode_t getRead_perm() {
    long cPtr = pc_ble_driver_sd_api_v5JNI.ble_gatts_attr_md_t_read_perm_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ble_gap_conn_sec_mode_t(cPtr, false);
  }

  public void setWrite_perm(ble_gap_conn_sec_mode_t value) {
    pc_ble_driver_sd_api_v5JNI.ble_gatts_attr_md_t_write_perm_set(swigCPtr, this, ble_gap_conn_sec_mode_t.getCPtr(value), value);
  }

  public ble_gap_conn_sec_mode_t getWrite_perm() {
    long cPtr = pc_ble_driver_sd_api_v5JNI.ble_gatts_attr_md_t_write_perm_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ble_gap_conn_sec_mode_t(cPtr, false);
  }

  public void setVlen(short value) {
    pc_ble_driver_sd_api_v5JNI.ble_gatts_attr_md_t_vlen_set(swigCPtr, this, value);
  }

  public short getVlen() {
    return pc_ble_driver_sd_api_v5JNI.ble_gatts_attr_md_t_vlen_get(swigCPtr, this);
  }

  public void setVloc(short value) {
    pc_ble_driver_sd_api_v5JNI.ble_gatts_attr_md_t_vloc_set(swigCPtr, this, value);
  }

  public short getVloc() {
    return pc_ble_driver_sd_api_v5JNI.ble_gatts_attr_md_t_vloc_get(swigCPtr, this);
  }

  public void setRd_auth(short value) {
    pc_ble_driver_sd_api_v5JNI.ble_gatts_attr_md_t_rd_auth_set(swigCPtr, this, value);
  }

  public short getRd_auth() {
    return pc_ble_driver_sd_api_v5JNI.ble_gatts_attr_md_t_rd_auth_get(swigCPtr, this);
  }

  public void setWr_auth(short value) {
    pc_ble_driver_sd_api_v5JNI.ble_gatts_attr_md_t_wr_auth_set(swigCPtr, this, value);
  }

  public short getWr_auth() {
    return pc_ble_driver_sd_api_v5JNI.ble_gatts_attr_md_t_wr_auth_get(swigCPtr, this);
  }

  public ble_gatts_attr_md_t() {
    this(pc_ble_driver_sd_api_v5JNI.new_ble_gatts_attr_md_t(), true);
  }

}
