/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class ble_gattc_conn_cfg_t {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ble_gattc_conn_cfg_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ble_gattc_conn_cfg_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pc_ble_driver_sd_api_v5JNI.delete_ble_gattc_conn_cfg_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setWrite_cmd_tx_queue_size(short value) {
    pc_ble_driver_sd_api_v5JNI.ble_gattc_conn_cfg_t_write_cmd_tx_queue_size_set(swigCPtr, this, value);
  }

  public short getWrite_cmd_tx_queue_size() {
    return pc_ble_driver_sd_api_v5JNI.ble_gattc_conn_cfg_t_write_cmd_tx_queue_size_get(swigCPtr, this);
  }

  public ble_gattc_conn_cfg_t() {
    this(pc_ble_driver_sd_api_v5JNI.new_ble_gattc_conn_cfg_t(), true);
  }

}
