/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class ble_gap_evt_sec_info_request_t {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ble_gap_evt_sec_info_request_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ble_gap_evt_sec_info_request_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pc_ble_driver_sd_api_v5JNI.delete_ble_gap_evt_sec_info_request_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setPeer_addr(ble_gap_addr_t value) {
    pc_ble_driver_sd_api_v5JNI.ble_gap_evt_sec_info_request_t_peer_addr_set(swigCPtr, this, ble_gap_addr_t.getCPtr(value), value);
  }

  public ble_gap_addr_t getPeer_addr() {
    long cPtr = pc_ble_driver_sd_api_v5JNI.ble_gap_evt_sec_info_request_t_peer_addr_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ble_gap_addr_t(cPtr, false);
  }

  public void setMaster_id(ble_gap_master_id_t value) {
    pc_ble_driver_sd_api_v5JNI.ble_gap_evt_sec_info_request_t_master_id_set(swigCPtr, this, ble_gap_master_id_t.getCPtr(value), value);
  }

  public ble_gap_master_id_t getMaster_id() {
    long cPtr = pc_ble_driver_sd_api_v5JNI.ble_gap_evt_sec_info_request_t_master_id_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ble_gap_master_id_t(cPtr, false);
  }

  public void setEnc_info(short value) {
    pc_ble_driver_sd_api_v5JNI.ble_gap_evt_sec_info_request_t_enc_info_set(swigCPtr, this, value);
  }

  public short getEnc_info() {
    return pc_ble_driver_sd_api_v5JNI.ble_gap_evt_sec_info_request_t_enc_info_get(swigCPtr, this);
  }

  public void setId_info(short value) {
    pc_ble_driver_sd_api_v5JNI.ble_gap_evt_sec_info_request_t_id_info_set(swigCPtr, this, value);
  }

  public short getId_info() {
    return pc_ble_driver_sd_api_v5JNI.ble_gap_evt_sec_info_request_t_id_info_get(swigCPtr, this);
  }

  public void setSign_info(short value) {
    pc_ble_driver_sd_api_v5JNI.ble_gap_evt_sec_info_request_t_sign_info_set(swigCPtr, this, value);
  }

  public short getSign_info() {
    return pc_ble_driver_sd_api_v5JNI.ble_gap_evt_sec_info_request_t_sign_info_get(swigCPtr, this);
  }

  public ble_gap_evt_sec_info_request_t() {
    this(pc_ble_driver_sd_api_v5JNI.new_ble_gap_evt_sec_info_request_t(), true);
  }

}
