/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class ble_gap_opt_t {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ble_gap_opt_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ble_gap_opt_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pc_ble_driver_sd_api_v5JNI.delete_ble_gap_opt_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setCh_map(ble_gap_opt_ch_map_t value) {
    pc_ble_driver_sd_api_v5JNI.ble_gap_opt_t_ch_map_set(swigCPtr, this, ble_gap_opt_ch_map_t.getCPtr(value), value);
  }

  public ble_gap_opt_ch_map_t getCh_map() {
    long cPtr = pc_ble_driver_sd_api_v5JNI.ble_gap_opt_t_ch_map_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ble_gap_opt_ch_map_t(cPtr, false);
  }

  public void setLocal_conn_latency(ble_gap_opt_local_conn_latency_t value) {
    pc_ble_driver_sd_api_v5JNI.ble_gap_opt_t_local_conn_latency_set(swigCPtr, this, ble_gap_opt_local_conn_latency_t.getCPtr(value), value);
  }

  public ble_gap_opt_local_conn_latency_t getLocal_conn_latency() {
    long cPtr = pc_ble_driver_sd_api_v5JNI.ble_gap_opt_t_local_conn_latency_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ble_gap_opt_local_conn_latency_t(cPtr, false);
  }

  public void setPasskey(ble_gap_opt_passkey_t value) {
    pc_ble_driver_sd_api_v5JNI.ble_gap_opt_t_passkey_set(swigCPtr, this, ble_gap_opt_passkey_t.getCPtr(value), value);
  }

  public ble_gap_opt_passkey_t getPasskey() {
    long cPtr = pc_ble_driver_sd_api_v5JNI.ble_gap_opt_t_passkey_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ble_gap_opt_passkey_t(cPtr, false);
  }

  public void setScan_req_report(ble_gap_opt_scan_req_report_t value) {
    pc_ble_driver_sd_api_v5JNI.ble_gap_opt_t_scan_req_report_set(swigCPtr, this, ble_gap_opt_scan_req_report_t.getCPtr(value), value);
  }

  public ble_gap_opt_scan_req_report_t getScan_req_report() {
    long cPtr = pc_ble_driver_sd_api_v5JNI.ble_gap_opt_t_scan_req_report_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ble_gap_opt_scan_req_report_t(cPtr, false);
  }

  public void setCompat_mode_1(ble_gap_opt_compat_mode_1_t value) {
    pc_ble_driver_sd_api_v5JNI.ble_gap_opt_t_compat_mode_1_set(swigCPtr, this, ble_gap_opt_compat_mode_1_t.getCPtr(value), value);
  }

  public ble_gap_opt_compat_mode_1_t getCompat_mode_1() {
    long cPtr = pc_ble_driver_sd_api_v5JNI.ble_gap_opt_t_compat_mode_1_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ble_gap_opt_compat_mode_1_t(cPtr, false);
  }

  public void setAuth_payload_timeout(ble_gap_opt_auth_payload_timeout_t value) {
    pc_ble_driver_sd_api_v5JNI.ble_gap_opt_t_auth_payload_timeout_set(swigCPtr, this, ble_gap_opt_auth_payload_timeout_t.getCPtr(value), value);
  }

  public ble_gap_opt_auth_payload_timeout_t getAuth_payload_timeout() {
    long cPtr = pc_ble_driver_sd_api_v5JNI.ble_gap_opt_t_auth_payload_timeout_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ble_gap_opt_auth_payload_timeout_t(cPtr, false);
  }

  public void setSlave_latency_disable(ble_gap_opt_slave_latency_disable_t value) {
    pc_ble_driver_sd_api_v5JNI.ble_gap_opt_t_slave_latency_disable_set(swigCPtr, this, ble_gap_opt_slave_latency_disable_t.getCPtr(value), value);
  }

  public ble_gap_opt_slave_latency_disable_t getSlave_latency_disable() {
    long cPtr = pc_ble_driver_sd_api_v5JNI.ble_gap_opt_t_slave_latency_disable_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ble_gap_opt_slave_latency_disable_t(cPtr, false);
  }

  public ble_gap_opt_t() {
    this(pc_ble_driver_sd_api_v5JNI.new_ble_gap_opt_t(), true);
  }

}
