/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class ble_gatts_cfg_attr_tab_size_t {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ble_gatts_cfg_attr_tab_size_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ble_gatts_cfg_attr_tab_size_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pc_ble_driver_sd_api_v5JNI.delete_ble_gatts_cfg_attr_tab_size_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setAttr_tab_size(long value) {
    pc_ble_driver_sd_api_v5JNI.ble_gatts_cfg_attr_tab_size_t_attr_tab_size_set(swigCPtr, this, value);
  }

  public long getAttr_tab_size() {
    return pc_ble_driver_sd_api_v5JNI.ble_gatts_cfg_attr_tab_size_t_attr_tab_size_get(swigCPtr, this);
  }

  public ble_gatts_cfg_attr_tab_size_t() {
    this(pc_ble_driver_sd_api_v5JNI.new_ble_gatts_cfg_attr_tab_size_t(), true);
  }

}
