/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class ble_l2cap_evt_ch_setup_request_t {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ble_l2cap_evt_ch_setup_request_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ble_l2cap_evt_ch_setup_request_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pc_ble_driver_sd_api_v5JNI.delete_ble_l2cap_evt_ch_setup_request_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setTx_params(ble_l2cap_ch_tx_params_t value) {
    pc_ble_driver_sd_api_v5JNI.ble_l2cap_evt_ch_setup_request_t_tx_params_set(swigCPtr, this, ble_l2cap_ch_tx_params_t.getCPtr(value), value);
  }

  public ble_l2cap_ch_tx_params_t getTx_params() {
    long cPtr = pc_ble_driver_sd_api_v5JNI.ble_l2cap_evt_ch_setup_request_t_tx_params_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ble_l2cap_ch_tx_params_t(cPtr, false);
  }

  public void setLe_psm(int value) {
    pc_ble_driver_sd_api_v5JNI.ble_l2cap_evt_ch_setup_request_t_le_psm_set(swigCPtr, this, value);
  }

  public int getLe_psm() {
    return pc_ble_driver_sd_api_v5JNI.ble_l2cap_evt_ch_setup_request_t_le_psm_get(swigCPtr, this);
  }

  public ble_l2cap_evt_ch_setup_request_t() {
    this(pc_ble_driver_sd_api_v5JNI.new_ble_l2cap_evt_ch_setup_request_t(), true);
  }

}
