/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class ble_gap_conn_sec_t {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ble_gap_conn_sec_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ble_gap_conn_sec_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pc_ble_driver_sd_api_v5JNI.delete_ble_gap_conn_sec_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setSec_mode(ble_gap_conn_sec_mode_t value) {
    pc_ble_driver_sd_api_v5JNI.ble_gap_conn_sec_t_sec_mode_set(swigCPtr, this, ble_gap_conn_sec_mode_t.getCPtr(value), value);
  }

  public ble_gap_conn_sec_mode_t getSec_mode() {
    long cPtr = pc_ble_driver_sd_api_v5JNI.ble_gap_conn_sec_t_sec_mode_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ble_gap_conn_sec_mode_t(cPtr, false);
  }

  public void setEncr_key_size(short value) {
    pc_ble_driver_sd_api_v5JNI.ble_gap_conn_sec_t_encr_key_size_set(swigCPtr, this, value);
  }

  public short getEncr_key_size() {
    return pc_ble_driver_sd_api_v5JNI.ble_gap_conn_sec_t_encr_key_size_get(swigCPtr, this);
  }

  public ble_gap_conn_sec_t() {
    this(pc_ble_driver_sd_api_v5JNI.new_ble_gap_conn_sec_t(), true);
  }

}
