/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class ble_evt_t {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ble_evt_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ble_evt_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pc_ble_driver_sd_api_v5JNI.delete_ble_evt_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setHeader(ble_evt_hdr_t value) {
    pc_ble_driver_sd_api_v5JNI.ble_evt_t_header_set(swigCPtr, this, ble_evt_hdr_t.getCPtr(value), value);
  }

  public ble_evt_hdr_t getHeader() {
    long cPtr = pc_ble_driver_sd_api_v5JNI.ble_evt_t_header_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ble_evt_hdr_t(cPtr, false);
  }

  public ble_evt_t() {
    this(pc_ble_driver_sd_api_v5JNI.new_ble_evt_t(), true);
  }

}
