/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class ble_pa_lna_cfg_t {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ble_pa_lna_cfg_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ble_pa_lna_cfg_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pc_ble_driver_sd_api_v5JNI.delete_ble_pa_lna_cfg_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setEnable(short value) {
    pc_ble_driver_sd_api_v5JNI.ble_pa_lna_cfg_t_enable_set(swigCPtr, this, value);
  }

  public short getEnable() {
    return pc_ble_driver_sd_api_v5JNI.ble_pa_lna_cfg_t_enable_get(swigCPtr, this);
  }

  public void setActive_high(short value) {
    pc_ble_driver_sd_api_v5JNI.ble_pa_lna_cfg_t_active_high_set(swigCPtr, this, value);
  }

  public short getActive_high() {
    return pc_ble_driver_sd_api_v5JNI.ble_pa_lna_cfg_t_active_high_get(swigCPtr, this);
  }

  public void setGpio_pin(short value) {
    pc_ble_driver_sd_api_v5JNI.ble_pa_lna_cfg_t_gpio_pin_set(swigCPtr, this, value);
  }

  public short getGpio_pin() {
    return pc_ble_driver_sd_api_v5JNI.ble_pa_lna_cfg_t_gpio_pin_get(swigCPtr, this);
  }

  public ble_pa_lna_cfg_t() {
    this(pc_ble_driver_sd_api_v5JNI.new_ble_pa_lna_cfg_t(), true);
  }

}
