/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class ble_gatts_evt_write_t {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ble_gatts_evt_write_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ble_gatts_evt_write_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pc_ble_driver_sd_api_v5JNI.delete_ble_gatts_evt_write_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setHandle(int value) {
    pc_ble_driver_sd_api_v5JNI.ble_gatts_evt_write_t_handle_set(swigCPtr, this, value);
  }

  public int getHandle() {
    return pc_ble_driver_sd_api_v5JNI.ble_gatts_evt_write_t_handle_get(swigCPtr, this);
  }

  public void setUuid(ble_uuid_t value) {
    pc_ble_driver_sd_api_v5JNI.ble_gatts_evt_write_t_uuid_set(swigCPtr, this, ble_uuid_t.getCPtr(value), value);
  }

  public ble_uuid_t getUuid() {
    long cPtr = pc_ble_driver_sd_api_v5JNI.ble_gatts_evt_write_t_uuid_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ble_uuid_t(cPtr, false);
  }

  public void setOp(short value) {
    pc_ble_driver_sd_api_v5JNI.ble_gatts_evt_write_t_op_set(swigCPtr, this, value);
  }

  public short getOp() {
    return pc_ble_driver_sd_api_v5JNI.ble_gatts_evt_write_t_op_get(swigCPtr, this);
  }

  public void setAuth_required(short value) {
    pc_ble_driver_sd_api_v5JNI.ble_gatts_evt_write_t_auth_required_set(swigCPtr, this, value);
  }

  public short getAuth_required() {
    return pc_ble_driver_sd_api_v5JNI.ble_gatts_evt_write_t_auth_required_get(swigCPtr, this);
  }

  public void setOffset(int value) {
    pc_ble_driver_sd_api_v5JNI.ble_gatts_evt_write_t_offset_set(swigCPtr, this, value);
  }

  public int getOffset() {
    return pc_ble_driver_sd_api_v5JNI.ble_gatts_evt_write_t_offset_get(swigCPtr, this);
  }

  public void setLen(int value) {
    pc_ble_driver_sd_api_v5JNI.ble_gatts_evt_write_t_len_set(swigCPtr, this, value);
  }

  public int getLen() {
    return pc_ble_driver_sd_api_v5JNI.ble_gatts_evt_write_t_len_get(swigCPtr, this);
  }

  public void setData(SWIGTYPE_p_unsigned_char value) {
    pc_ble_driver_sd_api_v5JNI.ble_gatts_evt_write_t_data_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getData() {
    long cPtr = pc_ble_driver_sd_api_v5JNI.ble_gatts_evt_write_t_data_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public ble_gatts_evt_write_t() {
    this(pc_ble_driver_sd_api_v5JNI.new_ble_gatts_evt_write_t(), true);
  }

}
