/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class ble_gap_privacy_params_t {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ble_gap_privacy_params_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ble_gap_privacy_params_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pc_ble_driver_sd_api_v5JNI.delete_ble_gap_privacy_params_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setPrivacy_mode(short value) {
    pc_ble_driver_sd_api_v5JNI.ble_gap_privacy_params_t_privacy_mode_set(swigCPtr, this, value);
  }

  public short getPrivacy_mode() {
    return pc_ble_driver_sd_api_v5JNI.ble_gap_privacy_params_t_privacy_mode_get(swigCPtr, this);
  }

  public void setPrivate_addr_type(short value) {
    pc_ble_driver_sd_api_v5JNI.ble_gap_privacy_params_t_private_addr_type_set(swigCPtr, this, value);
  }

  public short getPrivate_addr_type() {
    return pc_ble_driver_sd_api_v5JNI.ble_gap_privacy_params_t_private_addr_type_get(swigCPtr, this);
  }

  public void setPrivate_addr_cycle_s(int value) {
    pc_ble_driver_sd_api_v5JNI.ble_gap_privacy_params_t_private_addr_cycle_s_set(swigCPtr, this, value);
  }

  public int getPrivate_addr_cycle_s() {
    return pc_ble_driver_sd_api_v5JNI.ble_gap_privacy_params_t_private_addr_cycle_s_get(swigCPtr, this);
  }

  public void setP_device_irk(ble_gap_irk_t value) {
    pc_ble_driver_sd_api_v5JNI.ble_gap_privacy_params_t_p_device_irk_set(swigCPtr, this, ble_gap_irk_t.getCPtr(value), value);
  }

  public ble_gap_irk_t getP_device_irk() {
    long cPtr = pc_ble_driver_sd_api_v5JNI.ble_gap_privacy_params_t_p_device_irk_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ble_gap_irk_t(cPtr, false);
  }

  public ble_gap_privacy_params_t() {
    this(pc_ble_driver_sd_api_v5JNI.new_ble_gap_privacy_params_t(), true);
  }

}
