/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class ble_gatts_char_md_t {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ble_gatts_char_md_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ble_gatts_char_md_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pc_ble_driver_sd_api_v5JNI.delete_ble_gatts_char_md_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setChar_props(ble_gatt_char_props_t value) {
    pc_ble_driver_sd_api_v5JNI.ble_gatts_char_md_t_char_props_set(swigCPtr, this, ble_gatt_char_props_t.getCPtr(value), value);
  }

  public ble_gatt_char_props_t getChar_props() {
    long cPtr = pc_ble_driver_sd_api_v5JNI.ble_gatts_char_md_t_char_props_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ble_gatt_char_props_t(cPtr, false);
  }

  public void setChar_ext_props(ble_gatt_char_ext_props_t value) {
    pc_ble_driver_sd_api_v5JNI.ble_gatts_char_md_t_char_ext_props_set(swigCPtr, this, ble_gatt_char_ext_props_t.getCPtr(value), value);
  }

  public ble_gatt_char_ext_props_t getChar_ext_props() {
    long cPtr = pc_ble_driver_sd_api_v5JNI.ble_gatts_char_md_t_char_ext_props_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ble_gatt_char_ext_props_t(cPtr, false);
  }

  public void setP_char_user_desc(long value) {
    pc_ble_driver_sd_api_v5JNI.ble_gatts_char_md_t_p_char_user_desc_set(swigCPtr, this, value);
  }

  public long getP_char_user_desc() {
        long cPtr = pc_ble_driver_sd_api_v5JNI.ble_gatts_char_md_t_p_char_user_desc_get(swigCPtr, this);
        return cPtr;
    }

  public void setChar_user_desc_max_size(int value) {
    pc_ble_driver_sd_api_v5JNI.ble_gatts_char_md_t_char_user_desc_max_size_set(swigCPtr, this, value);
  }

  public int getChar_user_desc_max_size() {
    return pc_ble_driver_sd_api_v5JNI.ble_gatts_char_md_t_char_user_desc_max_size_get(swigCPtr, this);
  }

  public void setChar_user_desc_size(int value) {
    pc_ble_driver_sd_api_v5JNI.ble_gatts_char_md_t_char_user_desc_size_set(swigCPtr, this, value);
  }

  public int getChar_user_desc_size() {
    return pc_ble_driver_sd_api_v5JNI.ble_gatts_char_md_t_char_user_desc_size_get(swigCPtr, this);
  }

  public void setP_char_pf(ble_gatts_char_pf_t value) {
    pc_ble_driver_sd_api_v5JNI.ble_gatts_char_md_t_p_char_pf_set(swigCPtr, this, ble_gatts_char_pf_t.getCPtr(value), value);
  }

  public ble_gatts_char_pf_t getP_char_pf() {
    long cPtr = pc_ble_driver_sd_api_v5JNI.ble_gatts_char_md_t_p_char_pf_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ble_gatts_char_pf_t(cPtr, false);
  }

  public void setP_user_desc_md(ble_gatts_attr_md_t value) {
    pc_ble_driver_sd_api_v5JNI.ble_gatts_char_md_t_p_user_desc_md_set(swigCPtr, this, ble_gatts_attr_md_t.getCPtr(value), value);
  }

  public ble_gatts_attr_md_t getP_user_desc_md() {
    long cPtr = pc_ble_driver_sd_api_v5JNI.ble_gatts_char_md_t_p_user_desc_md_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ble_gatts_attr_md_t(cPtr, false);
  }

  public void setP_cccd_md(ble_gatts_attr_md_t value) {
    pc_ble_driver_sd_api_v5JNI.ble_gatts_char_md_t_p_cccd_md_set(swigCPtr, this, ble_gatts_attr_md_t.getCPtr(value), value);
  }

  public ble_gatts_attr_md_t getP_cccd_md() {
    long cPtr = pc_ble_driver_sd_api_v5JNI.ble_gatts_char_md_t_p_cccd_md_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ble_gatts_attr_md_t(cPtr, false);
  }

  public void setP_sccd_md(ble_gatts_attr_md_t value) {
    pc_ble_driver_sd_api_v5JNI.ble_gatts_char_md_t_p_sccd_md_set(swigCPtr, this, ble_gatts_attr_md_t.getCPtr(value), value);
  }

  public ble_gatts_attr_md_t getP_sccd_md() {
    long cPtr = pc_ble_driver_sd_api_v5JNI.ble_gatts_char_md_t_p_sccd_md_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ble_gatts_attr_md_t(cPtr, false);
  }

  public ble_gatts_char_md_t() {
    this(pc_ble_driver_sd_api_v5JNI.new_ble_gatts_char_md_t(), true);
  }

}
