/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class ble_gap_evt_auth_status_t {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ble_gap_evt_auth_status_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ble_gap_evt_auth_status_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pc_ble_driver_sd_api_v5JNI.delete_ble_gap_evt_auth_status_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setAuth_status(short value) {
    pc_ble_driver_sd_api_v5JNI.ble_gap_evt_auth_status_t_auth_status_set(swigCPtr, this, value);
  }

  public short getAuth_status() {
    return pc_ble_driver_sd_api_v5JNI.ble_gap_evt_auth_status_t_auth_status_get(swigCPtr, this);
  }

  public void setError_src(short value) {
    pc_ble_driver_sd_api_v5JNI.ble_gap_evt_auth_status_t_error_src_set(swigCPtr, this, value);
  }

  public short getError_src() {
    return pc_ble_driver_sd_api_v5JNI.ble_gap_evt_auth_status_t_error_src_get(swigCPtr, this);
  }

  public void setBonded(short value) {
    pc_ble_driver_sd_api_v5JNI.ble_gap_evt_auth_status_t_bonded_set(swigCPtr, this, value);
  }

  public short getBonded() {
    return pc_ble_driver_sd_api_v5JNI.ble_gap_evt_auth_status_t_bonded_get(swigCPtr, this);
  }

  public void setLesc(short value) {
    pc_ble_driver_sd_api_v5JNI.ble_gap_evt_auth_status_t_lesc_set(swigCPtr, this, value);
  }

  public short getLesc() {
    return pc_ble_driver_sd_api_v5JNI.ble_gap_evt_auth_status_t_lesc_get(swigCPtr, this);
  }

  public void setSm1_levels(ble_gap_sec_levels_t value) {
    pc_ble_driver_sd_api_v5JNI.ble_gap_evt_auth_status_t_sm1_levels_set(swigCPtr, this, ble_gap_sec_levels_t.getCPtr(value), value);
  }

  public ble_gap_sec_levels_t getSm1_levels() {
    long cPtr = pc_ble_driver_sd_api_v5JNI.ble_gap_evt_auth_status_t_sm1_levels_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ble_gap_sec_levels_t(cPtr, false);
  }

  public void setSm2_levels(ble_gap_sec_levels_t value) {
    pc_ble_driver_sd_api_v5JNI.ble_gap_evt_auth_status_t_sm2_levels_set(swigCPtr, this, ble_gap_sec_levels_t.getCPtr(value), value);
  }

  public ble_gap_sec_levels_t getSm2_levels() {
    long cPtr = pc_ble_driver_sd_api_v5JNI.ble_gap_evt_auth_status_t_sm2_levels_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ble_gap_sec_levels_t(cPtr, false);
  }

  public void setKdist_own(ble_gap_sec_kdist_t value) {
    pc_ble_driver_sd_api_v5JNI.ble_gap_evt_auth_status_t_kdist_own_set(swigCPtr, this, ble_gap_sec_kdist_t.getCPtr(value), value);
  }

  public ble_gap_sec_kdist_t getKdist_own() {
    long cPtr = pc_ble_driver_sd_api_v5JNI.ble_gap_evt_auth_status_t_kdist_own_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ble_gap_sec_kdist_t(cPtr, false);
  }

  public void setKdist_peer(ble_gap_sec_kdist_t value) {
    pc_ble_driver_sd_api_v5JNI.ble_gap_evt_auth_status_t_kdist_peer_set(swigCPtr, this, ble_gap_sec_kdist_t.getCPtr(value), value);
  }

  public ble_gap_sec_kdist_t getKdist_peer() {
    long cPtr = pc_ble_driver_sd_api_v5JNI.ble_gap_evt_auth_status_t_kdist_peer_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ble_gap_sec_kdist_t(cPtr, false);
  }

  public ble_gap_evt_auth_status_t() {
    this(pc_ble_driver_sd_api_v5JNI.new_ble_gap_evt_auth_status_t(), true);
  }

}
