/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class ble_gatt_char_ext_props_t {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ble_gatt_char_ext_props_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ble_gatt_char_ext_props_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pc_ble_driver_sd_api_v5JNI.delete_ble_gatt_char_ext_props_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setReliable_wr(short value) {
    pc_ble_driver_sd_api_v5JNI.ble_gatt_char_ext_props_t_reliable_wr_set(swigCPtr, this, value);
  }

  public short getReliable_wr() {
    return pc_ble_driver_sd_api_v5JNI.ble_gatt_char_ext_props_t_reliable_wr_get(swigCPtr, this);
  }

  public void setWr_aux(short value) {
    pc_ble_driver_sd_api_v5JNI.ble_gatt_char_ext_props_t_wr_aux_set(swigCPtr, this, value);
  }

  public short getWr_aux() {
    return pc_ble_driver_sd_api_v5JNI.ble_gatt_char_ext_props_t_wr_aux_get(swigCPtr, this);
  }

  public ble_gatt_char_ext_props_t() {
    this(pc_ble_driver_sd_api_v5JNI.new_ble_gatt_char_ext_props_t(), true);
  }

}
