/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class ble_common_opt_pa_lna_t {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ble_common_opt_pa_lna_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ble_common_opt_pa_lna_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pc_ble_driver_sd_api_v5JNI.delete_ble_common_opt_pa_lna_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setPa_cfg(ble_pa_lna_cfg_t value) {
    pc_ble_driver_sd_api_v5JNI.ble_common_opt_pa_lna_t_pa_cfg_set(swigCPtr, this, ble_pa_lna_cfg_t.getCPtr(value), value);
  }

  public ble_pa_lna_cfg_t getPa_cfg() {
    long cPtr = pc_ble_driver_sd_api_v5JNI.ble_common_opt_pa_lna_t_pa_cfg_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ble_pa_lna_cfg_t(cPtr, false);
  }

  public void setLna_cfg(ble_pa_lna_cfg_t value) {
    pc_ble_driver_sd_api_v5JNI.ble_common_opt_pa_lna_t_lna_cfg_set(swigCPtr, this, ble_pa_lna_cfg_t.getCPtr(value), value);
  }

  public ble_pa_lna_cfg_t getLna_cfg() {
    long cPtr = pc_ble_driver_sd_api_v5JNI.ble_common_opt_pa_lna_t_lna_cfg_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ble_pa_lna_cfg_t(cPtr, false);
  }

  public void setPpi_ch_id_set(short value) {
    pc_ble_driver_sd_api_v5JNI.ble_common_opt_pa_lna_t_ppi_ch_id_set_set(swigCPtr, this, value);
  }

  public short getPpi_ch_id_set() {
    return pc_ble_driver_sd_api_v5JNI.ble_common_opt_pa_lna_t_ppi_ch_id_set_get(swigCPtr, this);
  }

  public void setPpi_ch_id_clr(short value) {
    pc_ble_driver_sd_api_v5JNI.ble_common_opt_pa_lna_t_ppi_ch_id_clr_set(swigCPtr, this, value);
  }

  public short getPpi_ch_id_clr() {
    return pc_ble_driver_sd_api_v5JNI.ble_common_opt_pa_lna_t_ppi_ch_id_clr_get(swigCPtr, this);
  }

  public void setGpiote_ch_id(short value) {
    pc_ble_driver_sd_api_v5JNI.ble_common_opt_pa_lna_t_gpiote_ch_id_set(swigCPtr, this, value);
  }

  public short getGpiote_ch_id() {
    return pc_ble_driver_sd_api_v5JNI.ble_common_opt_pa_lna_t_gpiote_ch_id_get(swigCPtr, this);
  }

  public ble_common_opt_pa_lna_t() {
    this(pc_ble_driver_sd_api_v5JNI.new_ble_common_opt_pa_lna_t(), true);
  }

}
