/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public final class BLE_GATTS_SVCS {
  public final static BLE_GATTS_SVCS SD_BLE_GATTS_SERVICE_ADD = new BLE_GATTS_SVCS("SD_BLE_GATTS_SERVICE_ADD", 0xA0);
  public final static BLE_GATTS_SVCS SD_BLE_GATTS_INCLUDE_ADD = new BLE_GATTS_SVCS("SD_BLE_GATTS_INCLUDE_ADD");
  public final static BLE_GATTS_SVCS SD_BLE_GATTS_CHARACTERISTIC_ADD = new BLE_GATTS_SVCS("SD_BLE_GATTS_CHARACTERISTIC_ADD");
  public final static BLE_GATTS_SVCS SD_BLE_GATTS_DESCRIPTOR_ADD = new BLE_GATTS_SVCS("SD_BLE_GATTS_DESCRIPTOR_ADD");
  public final static BLE_GATTS_SVCS SD_BLE_GATTS_VALUE_SET = new BLE_GATTS_SVCS("SD_BLE_GATTS_VALUE_SET");
  public final static BLE_GATTS_SVCS SD_BLE_GATTS_VALUE_GET = new BLE_GATTS_SVCS("SD_BLE_GATTS_VALUE_GET");
  public final static BLE_GATTS_SVCS SD_BLE_GATTS_HVX = new BLE_GATTS_SVCS("SD_BLE_GATTS_HVX");
  public final static BLE_GATTS_SVCS SD_BLE_GATTS_SERVICE_CHANGED = new BLE_GATTS_SVCS("SD_BLE_GATTS_SERVICE_CHANGED");
  public final static BLE_GATTS_SVCS SD_BLE_GATTS_RW_AUTHORIZE_REPLY = new BLE_GATTS_SVCS("SD_BLE_GATTS_RW_AUTHORIZE_REPLY");
  public final static BLE_GATTS_SVCS SD_BLE_GATTS_SYS_ATTR_SET = new BLE_GATTS_SVCS("SD_BLE_GATTS_SYS_ATTR_SET");
  public final static BLE_GATTS_SVCS SD_BLE_GATTS_SYS_ATTR_GET = new BLE_GATTS_SVCS("SD_BLE_GATTS_SYS_ATTR_GET");
  public final static BLE_GATTS_SVCS SD_BLE_GATTS_INITIAL_USER_HANDLE_GET = new BLE_GATTS_SVCS("SD_BLE_GATTS_INITIAL_USER_HANDLE_GET");
  public final static BLE_GATTS_SVCS SD_BLE_GATTS_ATTR_GET = new BLE_GATTS_SVCS("SD_BLE_GATTS_ATTR_GET");
  public final static BLE_GATTS_SVCS SD_BLE_GATTS_EXCHANGE_MTU_REPLY = new BLE_GATTS_SVCS("SD_BLE_GATTS_EXCHANGE_MTU_REPLY");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static BLE_GATTS_SVCS swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + BLE_GATTS_SVCS.class + " with value " + swigValue);
  }

  private BLE_GATTS_SVCS(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private BLE_GATTS_SVCS(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private BLE_GATTS_SVCS(String swigName, BLE_GATTS_SVCS swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static BLE_GATTS_SVCS[] swigValues = { SD_BLE_GATTS_SERVICE_ADD, SD_BLE_GATTS_INCLUDE_ADD, SD_BLE_GATTS_CHARACTERISTIC_ADD, SD_BLE_GATTS_DESCRIPTOR_ADD, SD_BLE_GATTS_VALUE_SET, SD_BLE_GATTS_VALUE_GET, SD_BLE_GATTS_HVX, SD_BLE_GATTS_SERVICE_CHANGED, SD_BLE_GATTS_RW_AUTHORIZE_REPLY, SD_BLE_GATTS_SYS_ATTR_SET, SD_BLE_GATTS_SYS_ATTR_GET, SD_BLE_GATTS_INITIAL_USER_HANDLE_GET, SD_BLE_GATTS_ATTR_GET, SD_BLE_GATTS_EXCHANGE_MTU_REPLY };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

