/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class ble_gap_scan_params_t {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ble_gap_scan_params_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ble_gap_scan_params_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pc_ble_driver_sd_api_v5JNI.delete_ble_gap_scan_params_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setActive(short value) {
    pc_ble_driver_sd_api_v5JNI.ble_gap_scan_params_t_active_set(swigCPtr, this, value);
  }

  public short getActive() {
    return pc_ble_driver_sd_api_v5JNI.ble_gap_scan_params_t_active_get(swigCPtr, this);
  }

  public void setUse_whitelist(short value) {
    pc_ble_driver_sd_api_v5JNI.ble_gap_scan_params_t_use_whitelist_set(swigCPtr, this, value);
  }

  public short getUse_whitelist() {
    return pc_ble_driver_sd_api_v5JNI.ble_gap_scan_params_t_use_whitelist_get(swigCPtr, this);
  }

  public void setAdv_dir_report(short value) {
    pc_ble_driver_sd_api_v5JNI.ble_gap_scan_params_t_adv_dir_report_set(swigCPtr, this, value);
  }

  public short getAdv_dir_report() {
    return pc_ble_driver_sd_api_v5JNI.ble_gap_scan_params_t_adv_dir_report_get(swigCPtr, this);
  }

  public void setInterval(int value) {
    pc_ble_driver_sd_api_v5JNI.ble_gap_scan_params_t_interval_set(swigCPtr, this, value);
  }

  public int getInterval() {
    return pc_ble_driver_sd_api_v5JNI.ble_gap_scan_params_t_interval_get(swigCPtr, this);
  }

  public void setWindow(int value) {
    pc_ble_driver_sd_api_v5JNI.ble_gap_scan_params_t_window_set(swigCPtr, this, value);
  }

  public int getWindow() {
    return pc_ble_driver_sd_api_v5JNI.ble_gap_scan_params_t_window_get(swigCPtr, this);
  }

  public void setTimeout(int value) {
    pc_ble_driver_sd_api_v5JNI.ble_gap_scan_params_t_timeout_set(swigCPtr, this, value);
  }

  public int getTimeout() {
    return pc_ble_driver_sd_api_v5JNI.ble_gap_scan_params_t_timeout_get(swigCPtr, this);
  }

  public ble_gap_scan_params_t() {
    this(pc_ble_driver_sd_api_v5JNI.new_ble_gap_scan_params_t(), true);
  }

}
