/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class ble_l2cap_evt_ch_credit_t {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ble_l2cap_evt_ch_credit_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ble_l2cap_evt_ch_credit_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pc_ble_driver_sd_api_v5JNI.delete_ble_l2cap_evt_ch_credit_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setCredits(int value) {
    pc_ble_driver_sd_api_v5JNI.ble_l2cap_evt_ch_credit_t_credits_set(swigCPtr, this, value);
  }

  public int getCredits() {
    return pc_ble_driver_sd_api_v5JNI.ble_l2cap_evt_ch_credit_t_credits_get(swigCPtr, this);
  }

  public ble_l2cap_evt_ch_credit_t() {
    this(pc_ble_driver_sd_api_v5JNI.new_ble_l2cap_evt_ch_credit_t(), true);
  }

}
