/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class ble_gap_conn_params_t {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ble_gap_conn_params_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ble_gap_conn_params_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pc_ble_driver_sd_api_v5JNI.delete_ble_gap_conn_params_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setMin_conn_interval(int value) {
    pc_ble_driver_sd_api_v5JNI.ble_gap_conn_params_t_min_conn_interval_set(swigCPtr, this, value);
  }

  public int getMin_conn_interval() {
    return pc_ble_driver_sd_api_v5JNI.ble_gap_conn_params_t_min_conn_interval_get(swigCPtr, this);
  }

  public void setMax_conn_interval(int value) {
    pc_ble_driver_sd_api_v5JNI.ble_gap_conn_params_t_max_conn_interval_set(swigCPtr, this, value);
  }

  public int getMax_conn_interval() {
    return pc_ble_driver_sd_api_v5JNI.ble_gap_conn_params_t_max_conn_interval_get(swigCPtr, this);
  }

  public void setSlave_latency(int value) {
    pc_ble_driver_sd_api_v5JNI.ble_gap_conn_params_t_slave_latency_set(swigCPtr, this, value);
  }

  public int getSlave_latency() {
    return pc_ble_driver_sd_api_v5JNI.ble_gap_conn_params_t_slave_latency_get(swigCPtr, this);
  }

  public void setConn_sup_timeout(int value) {
    pc_ble_driver_sd_api_v5JNI.ble_gap_conn_params_t_conn_sup_timeout_set(swigCPtr, this, value);
  }

  public int getConn_sup_timeout() {
    return pc_ble_driver_sd_api_v5JNI.ble_gap_conn_params_t_conn_sup_timeout_get(swigCPtr, this);
  }

  public ble_gap_conn_params_t() {
    this(pc_ble_driver_sd_api_v5JNI.new_ble_gap_conn_params_t(), true);
  }

}
