/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class ble_gap_opt_passkey_t {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ble_gap_opt_passkey_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ble_gap_opt_passkey_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pc_ble_driver_sd_api_v5JNI.delete_ble_gap_opt_passkey_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setP_passkey(long value) {
    pc_ble_driver_sd_api_v5JNI.ble_gap_opt_passkey_t_p_passkey_set(swigCPtr, this, value);
  }

  public long getP_passkey() {
        long cPtr = pc_ble_driver_sd_api_v5JNI.ble_gap_opt_passkey_t_p_passkey_get(swigCPtr, this);
        return cPtr;
    }

  public ble_gap_opt_passkey_t() {
    this(pc_ble_driver_sd_api_v5JNI.new_ble_gap_opt_passkey_t(), true);
  }

}
