/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public final class BLE_COMMON_OPTS {
  public final static BLE_COMMON_OPTS BLE_COMMON_OPT_PA_LNA = new BLE_COMMON_OPTS("BLE_COMMON_OPT_PA_LNA", 0x01);
  public final static BLE_COMMON_OPTS BLE_COMMON_OPT_CONN_EVT_EXT = new BLE_COMMON_OPTS("BLE_COMMON_OPT_CONN_EVT_EXT");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static BLE_COMMON_OPTS swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + BLE_COMMON_OPTS.class + " with value " + swigValue);
  }

  private BLE_COMMON_OPTS(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private BLE_COMMON_OPTS(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private BLE_COMMON_OPTS(String swigName, BLE_COMMON_OPTS swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static BLE_COMMON_OPTS[] swigValues = { BLE_COMMON_OPT_PA_LNA, BLE_COMMON_OPT_CONN_EVT_EXT };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

