/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class ble_gatts_cfg_t {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ble_gatts_cfg_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ble_gatts_cfg_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pc_ble_driver_sd_api_v5JNI.delete_ble_gatts_cfg_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setService_changed(ble_gatts_cfg_service_changed_t value) {
    pc_ble_driver_sd_api_v5JNI.ble_gatts_cfg_t_service_changed_set(swigCPtr, this, ble_gatts_cfg_service_changed_t.getCPtr(value), value);
  }

  public ble_gatts_cfg_service_changed_t getService_changed() {
    long cPtr = pc_ble_driver_sd_api_v5JNI.ble_gatts_cfg_t_service_changed_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ble_gatts_cfg_service_changed_t(cPtr, false);
  }

  public void setAttr_tab_size(ble_gatts_cfg_attr_tab_size_t value) {
    pc_ble_driver_sd_api_v5JNI.ble_gatts_cfg_t_attr_tab_size_set(swigCPtr, this, ble_gatts_cfg_attr_tab_size_t.getCPtr(value), value);
  }

  public ble_gatts_cfg_attr_tab_size_t getAttr_tab_size() {
    long cPtr = pc_ble_driver_sd_api_v5JNI.ble_gatts_cfg_t_attr_tab_size_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ble_gatts_cfg_attr_tab_size_t(cPtr, false);
  }

  public ble_gatts_cfg_t() {
    this(pc_ble_driver_sd_api_v5JNI.new_ble_gatts_cfg_t(), true);
  }

}
