/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public final class BLE_L2CAP_SVCS {
  public final static BLE_L2CAP_SVCS SD_BLE_L2CAP_CH_SETUP = new BLE_L2CAP_SVCS("SD_BLE_L2CAP_CH_SETUP", 0xB0);
  public final static BLE_L2CAP_SVCS SD_BLE_L2CAP_CH_RELEASE = new BLE_L2CAP_SVCS("SD_BLE_L2CAP_CH_RELEASE");
  public final static BLE_L2CAP_SVCS SD_BLE_L2CAP_CH_RX = new BLE_L2CAP_SVCS("SD_BLE_L2CAP_CH_RX");
  public final static BLE_L2CAP_SVCS SD_BLE_L2CAP_CH_TX = new BLE_L2CAP_SVCS("SD_BLE_L2CAP_CH_TX");
  public final static BLE_L2CAP_SVCS SD_BLE_L2CAP_CH_FLOW_CONTROL = new BLE_L2CAP_SVCS("SD_BLE_L2CAP_CH_FLOW_CONTROL");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static BLE_L2CAP_SVCS swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + BLE_L2CAP_SVCS.class + " with value " + swigValue);
  }

  private BLE_L2CAP_SVCS(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private BLE_L2CAP_SVCS(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private BLE_L2CAP_SVCS(String swigName, BLE_L2CAP_SVCS swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static BLE_L2CAP_SVCS[] swigValues = { SD_BLE_L2CAP_CH_SETUP, SD_BLE_L2CAP_CH_RELEASE, SD_BLE_L2CAP_CH_RX, SD_BLE_L2CAP_CH_TX, SD_BLE_L2CAP_CH_FLOW_CONTROL };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

