/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class ble_l2cap_conn_cfg_t {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ble_l2cap_conn_cfg_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ble_l2cap_conn_cfg_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pc_ble_driver_sd_api_v5JNI.delete_ble_l2cap_conn_cfg_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setRx_mps(int value) {
    pc_ble_driver_sd_api_v5JNI.ble_l2cap_conn_cfg_t_rx_mps_set(swigCPtr, this, value);
  }

  public int getRx_mps() {
    return pc_ble_driver_sd_api_v5JNI.ble_l2cap_conn_cfg_t_rx_mps_get(swigCPtr, this);
  }

  public void setTx_mps(int value) {
    pc_ble_driver_sd_api_v5JNI.ble_l2cap_conn_cfg_t_tx_mps_set(swigCPtr, this, value);
  }

  public int getTx_mps() {
    return pc_ble_driver_sd_api_v5JNI.ble_l2cap_conn_cfg_t_tx_mps_get(swigCPtr, this);
  }

  public void setRx_queue_size(short value) {
    pc_ble_driver_sd_api_v5JNI.ble_l2cap_conn_cfg_t_rx_queue_size_set(swigCPtr, this, value);
  }

  public short getRx_queue_size() {
    return pc_ble_driver_sd_api_v5JNI.ble_l2cap_conn_cfg_t_rx_queue_size_get(swigCPtr, this);
  }

  public void setTx_queue_size(short value) {
    pc_ble_driver_sd_api_v5JNI.ble_l2cap_conn_cfg_t_tx_queue_size_set(swigCPtr, this, value);
  }

  public short getTx_queue_size() {
    return pc_ble_driver_sd_api_v5JNI.ble_l2cap_conn_cfg_t_tx_queue_size_get(swigCPtr, this);
  }

  public void setCh_count(short value) {
    pc_ble_driver_sd_api_v5JNI.ble_l2cap_conn_cfg_t_ch_count_set(swigCPtr, this, value);
  }

  public short getCh_count() {
    return pc_ble_driver_sd_api_v5JNI.ble_l2cap_conn_cfg_t_ch_count_get(swigCPtr, this);
  }

  public ble_l2cap_conn_cfg_t() {
    this(pc_ble_driver_sd_api_v5JNI.new_ble_l2cap_conn_cfg_t(), true);
  }

}
