/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public final class BLE_COMMON_SVCS {
  public final static BLE_COMMON_SVCS SD_BLE_ENABLE = new BLE_COMMON_SVCS("SD_BLE_ENABLE", 0x60);
  public final static BLE_COMMON_SVCS SD_BLE_EVT_GET = new BLE_COMMON_SVCS("SD_BLE_EVT_GET");
  public final static BLE_COMMON_SVCS SD_BLE_UUID_VS_ADD = new BLE_COMMON_SVCS("SD_BLE_UUID_VS_ADD");
  public final static BLE_COMMON_SVCS SD_BLE_UUID_DECODE = new BLE_COMMON_SVCS("SD_BLE_UUID_DECODE");
  public final static BLE_COMMON_SVCS SD_BLE_UUID_ENCODE = new BLE_COMMON_SVCS("SD_BLE_UUID_ENCODE");
  public final static BLE_COMMON_SVCS SD_BLE_VERSION_GET = new BLE_COMMON_SVCS("SD_BLE_VERSION_GET");
  public final static BLE_COMMON_SVCS SD_BLE_USER_MEM_REPLY = new BLE_COMMON_SVCS("SD_BLE_USER_MEM_REPLY");
  public final static BLE_COMMON_SVCS SD_BLE_OPT_SET = new BLE_COMMON_SVCS("SD_BLE_OPT_SET");
  public final static BLE_COMMON_SVCS SD_BLE_OPT_GET = new BLE_COMMON_SVCS("SD_BLE_OPT_GET");
  public final static BLE_COMMON_SVCS SD_BLE_CFG_SET = new BLE_COMMON_SVCS("SD_BLE_CFG_SET");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static BLE_COMMON_SVCS swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + BLE_COMMON_SVCS.class + " with value " + swigValue);
  }

  private BLE_COMMON_SVCS(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private BLE_COMMON_SVCS(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private BLE_COMMON_SVCS(String swigName, BLE_COMMON_SVCS swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static BLE_COMMON_SVCS[] swigValues = { SD_BLE_ENABLE, SD_BLE_EVT_GET, SD_BLE_UUID_VS_ADD, SD_BLE_UUID_DECODE, SD_BLE_UUID_ENCODE, SD_BLE_VERSION_GET, SD_BLE_USER_MEM_REPLY, SD_BLE_OPT_SET, SD_BLE_OPT_GET, SD_BLE_CFG_SET };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

