/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class ble_gap_data_length_limitation_t {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ble_gap_data_length_limitation_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ble_gap_data_length_limitation_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pc_ble_driver_sd_api_v5JNI.delete_ble_gap_data_length_limitation_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setTx_payload_limited_octets(int value) {
    pc_ble_driver_sd_api_v5JNI.ble_gap_data_length_limitation_t_tx_payload_limited_octets_set(swigCPtr, this, value);
  }

  public int getTx_payload_limited_octets() {
    return pc_ble_driver_sd_api_v5JNI.ble_gap_data_length_limitation_t_tx_payload_limited_octets_get(swigCPtr, this);
  }

  public void setRx_payload_limited_octets(int value) {
    pc_ble_driver_sd_api_v5JNI.ble_gap_data_length_limitation_t_rx_payload_limited_octets_set(swigCPtr, this, value);
  }

  public int getRx_payload_limited_octets() {
    return pc_ble_driver_sd_api_v5JNI.ble_gap_data_length_limitation_t_rx_payload_limited_octets_get(swigCPtr, this);
  }

  public void setTx_rx_time_limited_us(int value) {
    pc_ble_driver_sd_api_v5JNI.ble_gap_data_length_limitation_t_tx_rx_time_limited_us_set(swigCPtr, this, value);
  }

  public int getTx_rx_time_limited_us() {
    return pc_ble_driver_sd_api_v5JNI.ble_gap_data_length_limitation_t_tx_rx_time_limited_us_get(swigCPtr, this);
  }

  public ble_gap_data_length_limitation_t() {
    this(pc_ble_driver_sd_api_v5JNI.new_ble_gap_data_length_limitation_t(), true);
  }

}
