/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class ble_gatts_attr_t {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ble_gatts_attr_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ble_gatts_attr_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pc_ble_driver_sd_api_v5JNI.delete_ble_gatts_attr_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setP_uuid(ble_uuid_t value) {
    pc_ble_driver_sd_api_v5JNI.ble_gatts_attr_t_p_uuid_set(swigCPtr, this, ble_uuid_t.getCPtr(value), value);
  }

  public ble_uuid_t getP_uuid() {
    long cPtr = pc_ble_driver_sd_api_v5JNI.ble_gatts_attr_t_p_uuid_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ble_uuid_t(cPtr, false);
  }

  public void setP_attr_md(ble_gatts_attr_md_t value) {
    pc_ble_driver_sd_api_v5JNI.ble_gatts_attr_t_p_attr_md_set(swigCPtr, this, ble_gatts_attr_md_t.getCPtr(value), value);
  }

  public ble_gatts_attr_md_t getP_attr_md() {
    long cPtr = pc_ble_driver_sd_api_v5JNI.ble_gatts_attr_t_p_attr_md_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ble_gatts_attr_md_t(cPtr, false);
  }

  public void setInit_len(int value) {
    pc_ble_driver_sd_api_v5JNI.ble_gatts_attr_t_init_len_set(swigCPtr, this, value);
  }

  public int getInit_len() {
    return pc_ble_driver_sd_api_v5JNI.ble_gatts_attr_t_init_len_get(swigCPtr, this);
  }

  public void setInit_offs(int value) {
    pc_ble_driver_sd_api_v5JNI.ble_gatts_attr_t_init_offs_set(swigCPtr, this, value);
  }

  public int getInit_offs() {
    return pc_ble_driver_sd_api_v5JNI.ble_gatts_attr_t_init_offs_get(swigCPtr, this);
  }

  public void setMax_len(int value) {
    pc_ble_driver_sd_api_v5JNI.ble_gatts_attr_t_max_len_set(swigCPtr, this, value);
  }

  public int getMax_len() {
    return pc_ble_driver_sd_api_v5JNI.ble_gatts_attr_t_max_len_get(swigCPtr, this);
  }

  public void setP_value(long value) {
    pc_ble_driver_sd_api_v5JNI.ble_gatts_attr_t_p_value_set(swigCPtr, this, value);
  }

  public long getP_value() {
        long cPtr = pc_ble_driver_sd_api_v5JNI.ble_gatts_attr_t_p_value_get(swigCPtr, this);
        return cPtr;
    }

  public ble_gatts_attr_t() {
    this(pc_ble_driver_sd_api_v5JNI.new_ble_gatts_attr_t(), true);
  }

}
