/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public final class BLE_GAP_CFGS {
  public final static BLE_GAP_CFGS BLE_GAP_CFG_ROLE_COUNT = new BLE_GAP_CFGS("BLE_GAP_CFG_ROLE_COUNT", 0x80);
  public final static BLE_GAP_CFGS BLE_GAP_CFG_DEVICE_NAME = new BLE_GAP_CFGS("BLE_GAP_CFG_DEVICE_NAME");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static BLE_GAP_CFGS swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + BLE_GAP_CFGS.class + " with value " + swigValue);
  }

  private BLE_GAP_CFGS(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private BLE_GAP_CFGS(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private BLE_GAP_CFGS(String swigName, BLE_GAP_CFGS swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static BLE_GAP_CFGS[] swigValues = { BLE_GAP_CFG_ROLE_COUNT, BLE_GAP_CFG_DEVICE_NAME };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

