/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public final class BLE_GATTS_EVTS {
  public final static BLE_GATTS_EVTS BLE_GATTS_EVT_WRITE = new BLE_GATTS_EVTS("BLE_GATTS_EVT_WRITE", 0x50);
  public final static BLE_GATTS_EVTS BLE_GATTS_EVT_RW_AUTHORIZE_REQUEST = new BLE_GATTS_EVTS("BLE_GATTS_EVT_RW_AUTHORIZE_REQUEST");
  public final static BLE_GATTS_EVTS BLE_GATTS_EVT_SYS_ATTR_MISSING = new BLE_GATTS_EVTS("BLE_GATTS_EVT_SYS_ATTR_MISSING");
  public final static BLE_GATTS_EVTS BLE_GATTS_EVT_HVC = new BLE_GATTS_EVTS("BLE_GATTS_EVT_HVC");
  public final static BLE_GATTS_EVTS BLE_GATTS_EVT_SC_CONFIRM = new BLE_GATTS_EVTS("BLE_GATTS_EVT_SC_CONFIRM");
  public final static BLE_GATTS_EVTS BLE_GATTS_EVT_EXCHANGE_MTU_REQUEST = new BLE_GATTS_EVTS("BLE_GATTS_EVT_EXCHANGE_MTU_REQUEST");
  public final static BLE_GATTS_EVTS BLE_GATTS_EVT_TIMEOUT = new BLE_GATTS_EVTS("BLE_GATTS_EVT_TIMEOUT");
  public final static BLE_GATTS_EVTS BLE_GATTS_EVT_HVN_TX_COMPLETE = new BLE_GATTS_EVTS("BLE_GATTS_EVT_HVN_TX_COMPLETE");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static BLE_GATTS_EVTS swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + BLE_GATTS_EVTS.class + " with value " + swigValue);
  }

  private BLE_GATTS_EVTS(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private BLE_GATTS_EVTS(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private BLE_GATTS_EVTS(String swigName, BLE_GATTS_EVTS swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static BLE_GATTS_EVTS[] swigValues = { BLE_GATTS_EVT_WRITE, BLE_GATTS_EVT_RW_AUTHORIZE_REQUEST, BLE_GATTS_EVT_SYS_ATTR_MISSING, BLE_GATTS_EVT_HVC, BLE_GATTS_EVT_SC_CONFIRM, BLE_GATTS_EVT_EXCHANGE_MTU_REQUEST, BLE_GATTS_EVT_TIMEOUT, BLE_GATTS_EVT_HVN_TX_COMPLETE };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

