/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public final class sd_rpc_app_status_t {
  public final static sd_rpc_app_status_t PKT_SEND_MAX_RETRIES_REACHED = new sd_rpc_app_status_t("PKT_SEND_MAX_RETRIES_REACHED");
  public final static sd_rpc_app_status_t PKT_UNEXPECTED = new sd_rpc_app_status_t("PKT_UNEXPECTED");
  public final static sd_rpc_app_status_t PKT_ENCODE_ERROR = new sd_rpc_app_status_t("PKT_ENCODE_ERROR");
  public final static sd_rpc_app_status_t PKT_DECODE_ERROR = new sd_rpc_app_status_t("PKT_DECODE_ERROR");
  public final static sd_rpc_app_status_t PKT_SEND_ERROR = new sd_rpc_app_status_t("PKT_SEND_ERROR");
  public final static sd_rpc_app_status_t IO_RESOURCES_UNAVAILABLE = new sd_rpc_app_status_t("IO_RESOURCES_UNAVAILABLE");
  public final static sd_rpc_app_status_t RESET_PERFORMED = new sd_rpc_app_status_t("RESET_PERFORMED");
  public final static sd_rpc_app_status_t CONNECTION_ACTIVE = new sd_rpc_app_status_t("CONNECTION_ACTIVE");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static sd_rpc_app_status_t swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + sd_rpc_app_status_t.class + " with value " + swigValue);
  }

  private sd_rpc_app_status_t(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private sd_rpc_app_status_t(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private sd_rpc_app_status_t(String swigName, sd_rpc_app_status_t swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static sd_rpc_app_status_t[] swigValues = { PKT_SEND_MAX_RETRIES_REACHED, PKT_UNEXPECTED, PKT_ENCODE_ERROR, PKT_DECODE_ERROR, PKT_SEND_ERROR, IO_RESOURCES_UNAVAILABLE, RESET_PERFORMED, CONNECTION_ACTIVE };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

